-- ====================================================
-- 🔐 SUPABASE DATABASE SCHEMA FOR SHEETCODECREST
-- ====================================================
-- Copy and paste this script directly into your Supabase 
-- SQL Editor (Dashboard > SQL Editor > New Query) and click Run.

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    is_pro BOOLEAN DEFAULT FALSE,
    date_created TEXT,
    name TEXT,
    mobile TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create public access policies for simple web-based integration
CREATE POLICY "Allow public read/write access to users" 
ON public.users FOR ALL USING (true) WITH CHECK (true);


-- 2. Create Saved Records Table
CREATE TABLE IF NOT EXISTS public.records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES public.users(username) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    size BIGINT NOT NULL,
    mode TEXT NOT NULL,
    raw_rows JSONB DEFAULT '[]'::jsonb,
    table_headers JSONB DEFAULT '[]'::jsonb,
    data_profile JSONB,
    logistics_analytics JSONB,
    shopify_analytics JSONB,
    out_name TEXT NOT NULL,
    chat_history JSONB DEFAULT '[]'::jsonb,
    timestamp TEXT NOT NULL,
    comments JSONB DEFAULT '[]'::jsonb,
    versions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to records" 
ON public.records FOR ALL USING (true) WITH CHECK (true);


-- 3. Create Payments Log Table
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES public.users(username) ON DELETE SET NULL,
    gateway TEXT NOT NULL, -- 'stripe' or 'razorpay'
    payment_id TEXT NOT NULL,
    order_id TEXT,
    signature TEXT,
    amount NUMERIC NOT NULL,
    status TEXT NOT NULL, -- 'success', 'pending', etc.
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to payments" 
ON public.payments FOR ALL USING (true) WITH CHECK (true);


-- 4. Create Plans Table (Premium packages & access tiers)
CREATE TABLE IF NOT EXISTS public.plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    billing_period TEXT NOT NULL, -- 'monthly', 'yearly', 'lifetime', 'free'
    features JSONB DEFAULT '[]'::jsonb,
    is_active BOOLEAN DEFAULT TRUE,
    description TEXT,
    highlighted BOOLEAN DEFAULT FALSE,
    color TEXT DEFAULT '#f59e0b',
    max_reports INTEGER DEFAULT 0, -- 0 = unlimited
    sort_order INTEGER DEFAULT 99,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to plans" 
ON public.plans FOR ALL USING (true) WITH CHECK (true);


-- 5. Create Admin Activity Logs Table
CREATE TABLE IF NOT EXISTS public.admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    performed_by TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to admin_logs" 
ON public.admin_logs FOR ALL USING (true) WITH CHECK (true);


-- 6. Insert Default Plans
INSERT INTO public.plans (name, price, billing_period, features, is_active, description, highlighted, color, max_reports, sort_order)
VALUES 
('Starter Plan', 19.00, 'monthly', '["10 Excel analytics reports/mo", "Basic Logistics KPI dashboard", "Auto-resolve multi-SKU duplicates", "Support up to 1,000 orders/file"]'::jsonb, true, 'Great for growing local e-commerce sellers', false, '#10b981', 10, 1),
('Professional Pro', 49.00, 'monthly', '["Unlimited deep analytics reports", "Holt-Winters forecasting model", "Full courier efficiency dashboard", "Supabase cloud syncing & offline sync", "Imposed COD Premium Optimizer", "Priority developer support"]'::jsonb, true, 'Ultimate choice for professional e-commerce operations', true, '#3b82f6', 0, 2),
('Enterprise Premium', 199.00, 'yearly', '["All Pro features included", "Custom logistics integrations", "Multi-warehouse analysis", "Unlimited team workspaces", "Dedicated account manager"]'::jsonb, true, 'Designed for large-scale logistics and D2C brands', false, '#8b5cf6', 0, 3)
ON CONFLICT DO NOTHING;
