-- ====================================================
-- 🔐 SUPABASE DATABASE SCHEMA FOR SHEETCODECREST
-- ====================================================
-- Copy and paste this script directly into your Supabase 
-- SQL Editor (Dashboard > SQL Editor > New Query) and click Run.

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    is_pro BOOLEAN DEFAULT FALSE,
    date_created TEXT,
    name TEXT,
    mobile TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create public access policies for simple web-based integration
CREATE POLICY "Allow public read/write access to users" 
ON public.users FOR ALL USING (true) WITH CHECK (true);

-- 2. Create Saved Records Table
CREATE TABLE IF NOT EXISTS public.records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES public.users(username) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    size BIGINT NOT NULL,
    mode TEXT NOT NULL,
    raw_rows JSONB DEFAULT '[]'::jsonb,
    table_headers JSONB DEFAULT '[]'::jsonb,
    data_profile JSONB,
    logistics_analytics JSONB,
    shopify_analytics JSONB,
    out_name TEXT NOT NULL,
    chat_history JSONB DEFAULT '[]'::jsonb,
    timestamp TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to records" 
ON public.records FOR ALL USING (true) WITH CHECK (true);

-- 3. Create Payments Log Table
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES public.users(username) ON DELETE SET NULL,
    gateway TEXT NOT NULL, -- 'stripe' or 'razorpay'
    payment_id TEXT NOT NULL,
    order_id TEXT,
    signature TEXT,
    amount NUMERIC NOT NULL,
    status TEXT NOT NULL, -- 'success', 'pending', etc.
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to payments" 
ON public.payments FOR ALL USING (true) WITH CHECK (true);
